# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=120)),
                ('address_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=12)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('accomodation_count', models.SmallIntegerField()),
                ('bedroom_count', models.SmallIntegerField()),
                ('bed_count', models.SmallIntegerField()),
                ('bathroom_count', models.SmallIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.PropertyType'),
        ),
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.RoomType'),
        ),
        migrations.AddField(
            model_name='location',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Property'),
        ),
    ]
